### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by monstertony** [gabrielStanovsky/supervised-oie#5]
Hi,

When I am trying to train the model. I got the TypeError problem. Can anyone help? Thanks in advance!!!

`Traceback (most recent call last):
  File "./rnn/confidence_model.py", line 454, in <module>
    rnn.plot("./confidence_model.jpg", train_fn)
  File "./rnn/confidence_model.py", line 122, in plot
    X, Y = self.load_dataset(train_fn)
  File "./rnn/confidence_model.py", line 139, in load_dataset
    self.encode_outputs(sents))
  File "./rnn/confidence_model.py", line 208, in encode_outputs
    list(self.transform_labels(sent.label.values)),
  File "./rnn/confidence_model.py", line 110, in transform_labels
    classes  = list(self.classes_())
TypeError: 'NoneType' object is not iterable
`

**Comment by gabrielStanovsky** [comment]
Hi @monstertony, the maintenance of this project has moved to the [AllenNLP framework](https://allennlp.org/models#open-information-extraction). 
Please see a note about it at the main README file.
The training and prediction there are much simpler.
