### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by amritbhaskar** [gabrielStanovsky/supervised-oie#6]
Traceback (most recent call last):
  File "./rnn/confidence_model.py", line 462, in <module>
    rnn.set_model()
  File "./rnn/confidence_model.py", line 378, in set_model
    self.model = Model(input = map(itemgetter(0), true_input + corrupt_input),output = [output])
  File "/home/amrit/anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 1794, in __init__
    ' (missing Keras metadata).')
TypeError: Input tensors to a Model must be Keras tensors. Found: <map object at 0x7fbb3ee77ef0> (missing Keras metadata)

**Comment by gabrielStanovsky** [comment]
Hi @amritbhaskar , thank you for your report!
The maintenance of this project has moved to the AllenNLP framework.
Please see a note about it at the main README file.
The training and prediction there are much simpler.
